# Site settings
# in the templates available like {{ site.myvariable }}.
title: Clean portfolio theme for Jekyll powered by Bootstrap 4.
email: enoxaiming@naver.com
brand: En0xAiming
headline: On Top
description: > # this means to ignore newlines until "baseurl:"
  New Site
baseurl: "http://enoxaiming.github.io" # the subpath of your site, e.g. /blog
url: "http://enoxaiming.github.io" # the base hostname & protocol for your site
copyright: 2016 Whatever Company, Inc. All Rights Reserved.

# Build settings
markdown: kramdown

# Account ids
snapwidget: 247552

# Contacts
email: enoxaiming@naver.com
phone: +82 10-3801-9634

# Tracking
googleAnalitycsID: UA-83933844-1
